### ISSUE TITLE
Errors with ENOENT when directory is a dangling link

### ISSUE THREAD

**Issue by phated** [gulpjs/fs-mkdirp-stream#2]
I think we can either fix the error case or show a better error.  Ref https://github.com/cristianl/testcase-vinyl-bug

cc @erikkemperman

**Comment by phated** [comment]
@erikkemperman this probably got buried in other emails.  Do you have any thought on what the behavior should be for mkdirp'ing on a dangling symlink?

**Comment by erikkemperman** [comment]
@phated Sorry for late reply, pretty swamped just now... If the problem here is that we’re trying to create a directory under an ancestor which is a dangling link, I’d say throwing an error would be the correct thing to do.

Probably something went wrong earlier, and quietly replacing the dead link with a regular directory just makes that harder to track down.

Does that help?

**Comment by phated** [comment]
The issue is that `fs.stat` fails with ENOENT when called on a dangling link - which we propagate.  I think that's incorrect because something **does** exist on the filesystem, but it's that dangling link.  I was also thinking we could maybe create a directory that the dangling link is pointing at.  Not sure.

**Comment by phated** [comment]
@erikkemperman So `mkdir -p dangling-link/foo/bar` errors with `mkdir: dangling-link/foo/bar: Not a directory` but `mkdir -p symlink/foo/bar` does the mkdirp at the target of the link.  Maybe we should `lstat`/`readlink` and then mkdirp at the target?

**Comment by phated** [comment]
Otherwise we could continue to error but do it with a better message?  I want to determine the most intuitive behavior for this and don't necessarily want to mirror `mkdir -p`.

Also, this issue was brought to my attention because some user was trying to mkdirp at a dangling link.

**Comment by erikkemperman** [comment]
IMHO the behaviour of mkdir -p makes a lot of sense, actually, the "danger" being that we'd be obfuscating an earlier problem otherwise. And actually the error message I am now seeing on your `dangling-link` branch is decent enough, it seems to me, in that it mentions the missing target at least. A trace would be nice, but that's part of a larger issue if I've been tracking things properly?

**Comment by phated** [comment]
I guess it just feels wrong... I'm going to think on this some more.

**Comment by phated** [comment]
Comments that I forgot to tie this to:
https://github.com/gulpjs/gulp/issues/2086#issuecomment-356408620
https://github.com/gulpjs/gulp/issues/2086#issuecomment-356425017
